apiVersion: v1
kind: Service
metadata:
  name: mcp-wikipedia-server
  namespace: mcp
spec:
  type: NodePort
  selector:
    app: mcp-wikipedia-server
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      name: http
      protocol: TCP
